---
##########
- name: Create ISO file under tmp dir
  hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: block
    block: 
    - name: Get the original ISO
      get_url:
        url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.12/latest/rhcos-4.12.30-x86_64-live.x86_64.iso"
        dest: /tmp

    - name: Relace the isolinux.cfg file (x86_64)
      template:
        src: "isolinux.cfg-single.j2"
        dest: /tmp/isolinux.cfg
  
    - name: Relace the grub.cfg file (x86_64)
      template:
        src: "grub.cfg-single.j2"
        dest: /tmp/grub.cfg

    - name: "Customize ISO file"
      community.general.iso_customize:
        src_iso: "/tmp/rhcos-4.12.30-x86_64-live.x86_64.iso"
        dest_iso: "/shared/rhcos-4.12.30-x86_64-live.x86_64-customized.iso"
        delete_files:
          - "/EFI/redhat/grub.cfg"
          - "/isolinux/isolinux.cfg"
        add_files:
          - src_file: "/tmp/grub.cfg"
            dest_file: "/EFI/redhat/grub.cfg"
          - src_file: "/tmp/isolinux.cfg"
            dest_file: "/isolinux/isolinux.cfg"
 
    delegate_to: localhost

  - name: Another symbolic mode example, adding some permissions and removing others
    ansible.builtin.copy:
      src: /tmp/rhcos-4.12.30-x86_64-live.x86_64-customized.iso
      dest: /tmp/rhcos-4.12.30-x86_64-live.x86_64-customized.iso
